# Site
repository: TimonOmsk/timonomsk.github.io
favicon: images/favicon.ico

# Personal info
name: Dmitry Golushko, 32yrs
title: Golang Developer, Java Developer, Team Lead
email: dmitry@golushko.me
website: golushko.me
cv_link: https://golushko.me/images/DmitryGolushkoCV_short.docx
cv_name: Dmitry Golushko CV 

# Social links
instagram_username: timonomsk
linkedin_username: dgolushko
github_username: TimonOmsk

# About Section
# about_title: About Me
about_profile_image: images/personal.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dmitry and I'm a <mark>Golang Developer</mark> and ex-<mark>Java Developer</mark> with a good <mark>leadership</mark> and <mark>soft skills</mark>. 

  My hard skills strengths is:
  * 
  * Good knowledge of the JVM platform. Including <mark>JMM</mark> <mark>Multithreading</mark> <mark>Collections</mark>
  * I'm not afraid of <mark>legacy code</mark>(although as a typical developer I prefer the greenfield projects). 
  * I like to explore new technologies, and because of that I have wide knowledge in other programming languages(<mark>Javascript</mark> <mark>C#</mark> <mark>Lua</mark>)
    
  My soft skills strengths 
  * <mark>Leadership</mark>
  * <mark>Responsibility</mark>. And by "responsibility" I mean that I'm ready to take responsibility for a feature, for a team, for a project.
  * I tried the different versions of <mark>Scrum</mark> :) From ScrumBut to canonical Scrum
  * I made about 100 <mark>interviews</mark> for java developer position(with different seniority level, from juniors to seniors)
  * Experience in <mark>team transformation</mark>
  * Experience in <mark>building a team</mark>(and a project) from the scratch

  A little bit of personal philosophy
  
  The main motivation for me is a result. If something should be done to move a project forward - I will do it.
  Develop some new features, refactor legacy code, meeting facilitation, junior developers mentoring, making analytical research. It doesn't matter. 
  If it helps my team if it helps my project if it helps my company. I will do it. 


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Kasten by Veeam
        link: https://kasten.io
        sub_title: Software Developer
        caption: November 2021 - Present
        quote: >
          <mark>Golang</mark> <mark>Kubernetes</mark> <mark>Helm</mark>
        description: |
          Working on all parts of K10 by Veeam. 
      - layout: left
        title: Micro Focus - Fortify Static Code Analyzer
        link: https://www.microfocus.com/en-us/products/static-code-analysis-sast/overview
        sub_title: Senior Software Engineer
        caption: May 2020 - November 2021
        quote: >
          <mark>Golang</mark> <mark>Java</mark> <mark>Fortify</mark> <mark>SAST</mark>
        description: |
          Compiler frontend for Golang language. Frontend translates Golang code to internal Fortify SCA language. 
      - layout: left
        title: Neolab
        link: neolab.io
        sub_title: Lead Java Developer, Project tech lead
        caption: February 2018 - May 2020 (remote since May`19)
        quote: >
          <mark>Java</mark> <mark>Akka</mark> <mark>Netty</mark> <mark>PostgreSQL</mark> <mark>Agile</mark> <mark>Scrum</mark> <mark>People Management</mark> <mark>Interviews</mark> <mark>Lead</mark>
        description: | # this will include new lines to allow paragraphs
          I can split my work into two parts. The first part is the programming. It was around 70% of all time.
          The backend team was very stable for the last couple of years so I was hired as a skilled developer to bring some new wave into the team. 
          I made a lot of little improvements in terms of development processes and tools. But the most part of my programming time was dedicated to refactoring.
          Many core parts of the backend system were refactored. Speaking of technologies it was mostly <mark>JavaSE</mark> development including <mark>Multithreading</mark>, <mark>Network</mark>, <mark>Algos</mark> and so on.

          The second part was the <mark>leadership</mark> part. As a Lead Java Developer, I was focused on increasing performance and making the working process more comfortable for the team.
          We made a lot of work on <mark>communications</mark> and <mark>transparency</mark> inside the team(daily meetings, retrospectives, code style guides, code review practice). 
          Coaching, inspiration, motivation, facilitation... Everything that a typical lead should do :)

          In the last couple of months, I'm working as a <mark>Project Lead</mark>. There were a lot of small "achievements" for past months, so it's very hard to describe them.
          The only reasonable thing that I can do is to describe my duties and say that the project is progressing very well :) 

          My duties as a Project lead: 
            * To build and keep <mark>effective сommunications</mark> between teams.
            * To keep the teams <mark>focused on project's goals</mark>
            * Provide <mark>support</mark> to the development teams, business, and external partners.
            * Keep the project <mark>on the track</mark>
            * Resolve conflicts, bottlenecks, and other problems which are connected to the technical part of the project

      - layout: left
        title: Luxoft (Customer - BT Global Services)
        link: luxoft.com
        sub_title: Application Securiy Analyst
        caption: October 2017 - February 2018
        quote: >
          <mark>Java</mark> <mark>Micro Focus Fortify</mark> <mark>OWASP</mark> <mark>Application Security</mark> <mark>SonarQube</mark>
        description: | # this will include new lines to allow paragraphs       
          A little experiment with another specialization. I learned about tools for security and penetration testing, typical applications' vulnerabilities(XSS, SQL Injection, Clickjacking, etc.) and other security risks.
          My duties were reviewing source code to find potential vulnerabilities and provide recommendations for avoiding those vulnerabilities.

      - layout: left
        title: Luxoft (Customer - Raiffeisen Russia)
        link: luxoft.com
        sub_title: Lead Java Developer
        caption: April 2016 - September 2017
        quote: >
          <mark>Java</mark> <mark>Spring</mark> <mark>Hibernate</mark> <mark>IBM DB2</mark> <mark>HTML</mark> <mark>CSS</mark> <mark>Javascript</mark>
        description: | # this will include new lines to allow paragraphs
          Project for communication between the bank and the Federal Tax Department

          From the tech side, it was a typical enterprise project with Spring and Hibernate on the backend and HTML, CSS, Jquery on the frontend. Nothing special, no rocket science.
          The most interesting part here was Scrum. Or rather that it was a great team of professionals with a project which was perfectly suitable for Scrum.
          Really amazing experience with canonical Scrum. This experience gave me an understanding of how Scrum should work and what type of projects are fits Scrum best.
          
          Additional things that deserve to be noticed 
          * Dozens of interviews for the Corporate Junior Programm
          * Mentoring junior developers from the Corporate Junior Programm

          

      - layout: left
        title: EST Technologies
        link: estaxi.ru
        sub_title: Senior Java Developer, Backend department
        caption: June 2012 - April 2016
        quote: > 
          <mark>Java</mark> <mark>Netty</mark> <mark>Cassandra</mark> <mark>PostgreSQL</mark> <mark>Vertx.io</mark> <mark>Elasticsearch</mark> <mark>Akka</mark> <mark>Grails</mark>
        description: | # this will include new lines to allow paragraphs
          EST Technologies was focused on creating a B2B system for the complete automatization of taxi companies. Applications for drivers, passengers and dispatchers, billing, IP telephony, and SMS,
          the market of orders(one taxi company was able to sell order to another company).
          Very interesting job primarily because of gained technical experience. There were about 100 geographically distributed servers with low quality of internet connection. 
          So we had strict requirements about the efficiency of communication protocols and the amount of data transferring between servers.
          
          Most interesting technologies 
          - Elastisearch for a search for destinations(streets, places, etc.) 
          - Cassandra for removing SPOF
          - Akka, Kafka and Tarantool(tarantool.io, In-memory DB) for collecting real-time information about drivers and for orders distribution.
          - ZeroMQ for communication between servers(honestly, that was a failure, because ZeroMQ is not very tolerant of connections with low quality)
        
      - layout: left
        title: Gehtsoft
        link: gehtsoft.ru
        sub_title: Software Engineer in Test
        caption: June 2008 - June 2012
        quote: >
          <mark>Java</mark> <mark>Lua</mark> <mark>C#</mark> <mark>VBA</mark> <mark>Forex</mark> <mark>Automated trading</mark>
        description: | # this will include new lines to allow paragraphs        
          - Development of automated tests for the Forex trading API 
          - Development of automated trading advisors for the forex market(Lua, C#, C++, VBA)    
          - Testing Automated Trading Advisors and Technical Indicators for the FXCM Trading Station Platform. Advisors and indicators were written in Lua programming language
  title: Trainings
  layout: list
    content: 
      - layout: left
        title: Luxoft Leadership Academy
        caption: 2017
        description: | # this will include new lines to allow paragraphs
          Internal training for lead developers and team leads. 

      - layout: left
        title: PROFESSIONAL SCRUM FOUNDATIONS™ TRAINING
        caption: 2017
        description: | # this will include new lines to allow paragraphs
          Professional Scrum Foundations™ (PSF) is a 2-day course that provides the foundational knowledge needed to work with Scrum in a highly practical way. The course is a combination of instruction and team based exercises where students experience how the Scrum framework improves product delivery efforts. 

      - layout: left
        title: Languages  
        description: | # this will include new lines to allow paragraphs
          * <mark>Russian</mark> - Native
          * <mark>English</mark> - Professional working proficiency
          * <mark>Czech</mark> - Elementary proficiency

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  You won't find any of my projects in open source. It's not because I'm a lazy person :) 
  I would better make some additional stuff for my main job(helpful utils, research, experiments).
  My job is always my hobby and I will do my best to achieve my current project's goals. 
  
  But job is not the only thing that I like :) So here is some things that I like besides my job
  * Collectible card games like Magic The Gathering, Gwent.  
  * Cars. I really enjoy driving. I can spend hours just driving around the city. 
  * My family :) 


# Footer
footer_show_references: true

# Build settings
remote_theme: TimonOmsk/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
